# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: students_details.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "images.Empty" do
  end
  add_message "images.HelloRequest" do
    optional :name, :string, 1
  end
  add_message "images.HelloResponse" do
    optional :body, :string, 1
  end
end

module Images
  Empty = Google::Protobuf::DescriptorPool.generated_pool.lookup("images.Empty").msgclass
  HelloRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("images.HelloRequest").msgclass
  HelloResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("images.HelloResponse").msgclass
end
