# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: images.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "images.Empty" do
  end
  add_message "images.ImgRequest" do
    optional :noCache, :int64, 1
    optional :top, :int64, 2
  end
  add_message "images.HelloRequest" do
    optional :name, :string, 1
  end
  add_message "images.HelloResponse" do
    optional :body, :string, 1
  end
  add_message "images.Images" do
    repeated :images, :message, 1, "images.Image"
  end
  add_message "images.Image" do
    optional :descripcion, :string, 1
    optional :accesos, :int64, 2
    optional :imagen, :string, 3
  end
end

module Images
  Empty = Google::Protobuf::DescriptorPool.generated_pool.lookup("images.Empty").msgclass
  ImgRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("images.ImgRequest").msgclass
  HelloRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("images.HelloRequest").msgclass
  HelloResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("images.HelloResponse").msgclass
  Images = Google::Protobuf::DescriptorPool.generated_pool.lookup("images.Images").msgclass
  Image = Google::Protobuf::DescriptorPool.generated_pool.lookup("images.Image").msgclass
end
